[package]
name = "phrasedos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
nova-scotia = "0.5.0"
nova-snark = "0.23.0"
serde_json = "1.0.107"
