[workspace]

members = [
    "crates/phrasedos_cli",
    # "crates/phrasedos_circuit"
]
# default-members = ["crates/phrasedos_circuit"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"

[workspace.dependencies]
nova-scotia = "0.5.0"
nova-snark = "0.23.0"
serde_json = "1.0.107"