[workspace]

members = [
    "crates/phrasedos_cli",
    "crates/phrasedos_nova",
    "crates/phrasedos_server"
]
default-members = ["crates/phrasedos_cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"

[workspace.dependencies]
nova-scotia = { git = "https://github.com/nalinbhardwaj/Nova-Scotia/" }
nova-snark = "0.23.0"
phrasedos_nova = { path = "crates/phrasedos_nova" }
serde_json = "1.0.107"
serde = "1.0.190"