[workspace]

members = [
    "crates/grapevine_cli",
    "crates/grapevine_circuits",
    "crates/grapevine_server"
]
default-members = ["crates/grapevine_cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"

[workspace.dependencies]
nova-scotia = { git = "https://github.com/nalinbhardwaj/Nova-Scotia/" }
nova-snark = "0.23.0"
grapevine_circuits = { path = "crates/grapevine_circuits" }
serde_json = "1.0.107"
serde = "1.0.190"
rand = "0.8.5"