version: '3'
services:
  mongo:
    restart: on-failure
    image: mongo:6-jammy
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
     - ./db:/data/db

  mongo-express:
    restart: on-failure
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"


# env_file:
#   - ../.env