[package]
name = "grapevine_cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
nova-scotia.workspace = true
nova-snark.workspace = true
grapevine_circuits.workspace = true
serde = "1.0.190"
serde_json.workspace = true
rand = "0.8.5"
babyjubjub-rs = "0.0.10"
num-bigint = "0.4.4"
sha256 = "1.4.0"
poseidon-rs = "0.0.10"
ff = { package="ff_ce" , version= "0.11", features = ["derive"] }
aes = "0.8.3"
cbc = "0.1.2"
hex = "0.4.3"
hex-literal = "0.4.1"

[[bin]]
name = "grapevine"
path = "src/main.rs"
