[package]
name = "phrasedos_nova"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nova-scotia.workspace = true
nova-snark.workspace = true
serde_json.workspace = true
serde.workspace = true
hex = "0.4.3"
